Added scrollTo action.
SunriseDigital/simple-selenium-checker pull request #3
Opened 2017-09-19 05:18 UTC by tomita-ychr

## What's change
The page scrolling function was added to action.js.
Please merge to master branch, if you like.

## Sample
```js
actions: [
  {scrollTo: 500}
]
```

2017-09-19 06:00 UTC, gomo requested changes

2017-09-19 06:00 UTC, gomo commented on src/actions.js
> +  checker.driver.executeScript("window.scrollTo(0," + coord + ")");
Your code only supports vertical scrolling, but please also support horizontal scrolling.

```js
{scrollTo: {x: 0, y: 100}}
```

I think that it is good to pass arguments as objects, and for axes omitted, set 0 to the default value.

2017-09-19 06:01 UTC, gomo commented on src/actions.js
> +  checker.driver.executeScript("window.scrollTo(0," + coord + ")");
Please write test too.

2017-09-20 03:34 UTC, tomita-ychr commented
@gomo Fix for https://github.com/SunriseDigital/simple-selenium-checker/pull/3#pullrequestreview-63556158 .
Please check it out again.

2017-09-21 04:00 UTC, gomo approved these changes
LGTM 👍

2017-09-21 04:00 UTC, merged