Added while loop function to Checker.
SunriseDigital/simple-selenium-checker pull request #4
Opened 2017-09-28 04:34 UTC by tomita-ychr

## What's change?
I tried changing Checker.js so that a dynamic loop like `while` statement can be done during automatic test.
Please merge to master branch, if you like.

## Sample
Please refer to the following test code.
https://github.com/tomita-ychr/simple-selenium-checker/blob/65d1861b890c6c143dff32c2a68ea5a5013003a5/tests/ssc.js#L1339-L1357

2017-09-29 06:42 UTC, gomo commented
Please update docs

2017-09-29 07:24 UTC, tomita-ychr commented
@gomo I updated the docs with https://github.com/SunriseDigital/simple-selenium-checker/pull/4/commits/e48fbfbebf68114859d5f3d2edb5effcb7563baf.
Please check again.

2017-10-02 06:47 UTC, gomo requested changes

2017-10-02 06:47 UTC, gomo commented on README.md
> +If there is a "while" directive, nested "scenario" continues as long as the condition is satisfied.
* continuesだと繰り返し実行されるニュアンスが伝わりづらいと思いました。実行という言葉を盛り込んだ方がいいかも。
* conditionsと複数にした方がいいですね。
* nested "scenario"の目的語？というのかな？何にネストされてるの？という疑問が湧く。
* the conditionのtheは唐突な感じします。`{while: {condition: []}}`とかなってるならtheでもいいかもしれないけど。

If you specify conditions in the while directive, the specified scenario continues to run while the conditions are satisfied.

とかどうかな？

If there are conditions in a "while" directive, というのも考えたけど、これだと「whileディレクティブに条件があると」というニュアンスになるのでちょっと違いますよね。なので主語をyouにしました。

the specified scenarioはthe specified scenario in that directiveだけど、冗長な気がしたので省略しても伝わるような気がする。

😇

2017-10-02 07:13 UTC, tomita-ychr commented
> If you specify conditions in the while directive, the specified scenario continues to run while the conditions are satisfied.
>
> とかどうかな？

@gomo 
確かにこれで十分伝わりますね。
specify conditions と specified scenario で説明が流れるように並んでいて、こちらのほうが頭から順に訳していけばすんなり理解できます。なので英語としてもわかりやすいと感じました。
こちらの案を使わせていただきます！

英語でPR出したり、短いながらドキュメント書いてみましたがたまにはこういうのもすごく勉強になります。

2017-10-02 07:13 UTC, tomita-ychr commented on README.md
> +If there is a "while" directive, nested "scenario" continues as long as the condition is satisfied.
> If you specify conditions in the while directive, the specified scenario continues to run while the conditions are satisfied.
>
> とかどうかな？

@gomo 
確かにこれで十分伝わりますね。
specify conditions と specified scenario で説明が流れるように並んでいて、こちらのほうが頭から順に訳していけばすんなり理解できます。なので英語としてもわかりやすいと感じました。
こちらの案を使わせていただきます！

英語でPR出したり、短いながらドキュメント書いてみましたがたまにはこういうのもすごく勉強になります。

2017-10-03 02:35 UTC, merged