Compatible with SSL
SunriseDigital/simple-selenium-checker pull request #7
Opened 2017-10-12 03:05 UTC by tomita-ychr

## 概要
自動テスト実行時にコンソールに出力される `Mixed Content` をチェックし、エラーとして検出させる動作を追加しました。

主な変更点は下記のとおりです。

- ブラウザのコンソールに出力される `Mixed Content` のチェックを追加
- ページ内で読み込まれている画像、CSSなどのファイルの存在チェックを追加
- ユニットテストを https で接続するように変更

特に問題ないようでしたら master へマージしていただければと思います。
よろしくお願いします。

2017-10-16 06:52 UTC, gomo requested changes

2017-10-16 06:52 UTC, gomo commented on src/Checker.js
> +  _ignoreConsoleCheck(log){
これはちょっと意図が伝わってなかった・・・使う側のクライアントコードでコントロールできないと意味ないやん。ここに作るものではないです。

😇

2017-10-16 06:52 UTC, gomo commented on src/Checker.js
> +                  if(this._ignoreConsoleCheck && this._ignoreConsoleCheck(log) !== true){
これは配列にした方が使い勝手が良さそう。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/some
someを使って上手いことやってください。

😇

2017-10-16 06:52 UTC, gomo commented on tests/ssc.js
> +  })
ignoreのテストも追加お願いします。

😇

2017-10-18 02:42 UTC, gomo requested changes

2017-10-18 02:42 UTC, gomo commented on README.md
> +If use `ignoreConsoleCheck`, you can ignore the error you specified during test execution.
```
you can ignore the console error specified during test execution.
```

consoleと入れてやった方がピンとくると思った。theになってるので伝わるかと思うけど・・・日本人が読んだときにわかりやすいかな。あとyou specifedがくどいと思った。

細かいけどお願いします。

😇

2017-10-18 02:42 UTC, gomo commented on tests/ssc.js
> +    checker.ignoreConsoleCheck.push("Mixed Content")
あ、いや、これはそういうわけじゃないですね。

```
checker.addIgnoreConsoleCheck(log => ....)
```

テキストを渡す仕様だと、不確かなチェックしかできないので、関数をAddするようにしてください。

なぜテキストを追加するように変えたのか？ :scream:

2017-10-18 02:49 UTC, tomita-ychr commented on src/Checker.js
> +                  if(this.ignoreConsoleCheck && this.ignoreConsoleCheck.some(target => log.message.indexOf(target) != -1)){
target は関数にする

2017-10-20 02:23 UTC, gomo requested changes

2017-10-20 02:23 UTC, gomo commented on src/Checker.js
> +                  if(this.ignoreConsoleCheck && this.ignoreConsoleCheck.some(func => func(log) == true)){
ドキュメントが`Please return true if it is an ignore target.`と書いてあるので、これは`=== true`の方がいいですね。ドキュメントを直す手もありますけど、私の好みとしては`===`がいいかな。

😇

2017-10-23 05:06 UTC, gomo approved these changes
👍

2017-10-23 05:06 UTC, merged