Changed to be able to pass placeholder or text to append method
SunriseDigital/simple-selenium-checker pull request #9
Opened 2017-12-06 09:51 UTC by naveqo

# 概要

appendにplaceholderも渡せるように変更しました。

問題ないようでしたらmasterにマージをお願い致します。

2017-12-07 03:44 UTC, gomo requested changes

2017-12-07 03:44 UTC, gomo commented on tests/ssc.js
> +        url: placeholder('url').append('/append-placeholder.html?').append(placeholder('queryString')).append('=on')
appendに渡したplaceholderもappendが可能かどうかテストを追加してもらえますか？両方あるといいので
```js
placeholder('url').append('/').append(placeholder('fileName')).append('?').append(placeholder('queryString').append('_foo')).append('=on')
```
という感じがいいかも。

😇

2017-12-07 04:24 UTC, naveqo commented on tests/ssc.js
> +        url: placeholder('url').append('/append-placeholder.html?').append(placeholder('queryString')).append('=on')
承知しました！！

2017-12-08 02:56 UTC, gomo approved these changes
👍

2017-12-08 05:44 UTC, merged